### ISSUE TITLE
Film emulation presets are not saved

### ISSUE THREAD

**Issue by mexicarne** [dtschump/gmic-minimal#3]
Hello,

I'm testing GMIC plugin 1.6.8 on FreeBSD and can't understand two things:
* Where in filesystem `cli_update168.gmic` and `gimp_update168.gmic` files should be put to?
* Why my `~/.gmic_film_presets` still empty when applying filters from "Film Emulation" category?

Right now I put cli_update168.gmic and gimp_update168.gmic to gimp plugins dir (/usr/local/libexec/gimp/2.2/plug-ins) and can't be sure if they are accessible by gimp_gmic or not. 

Thank you!

**Comment by dtschump** [comment]
Now, G'MIC stores its configuration file in `$HOME/.config/gmic/`
(freedesktop convention).

**Comment by mexicarne** [comment]
Thanks, I see *.cimgz in this directory! 

So what about cli_update168.gmic and gimp_update168.gmic files? User supposed to put them manually into `$HOME/.config/gmic/`? Can I anyhow make them available system-wide, to make FreeBSD package all the thankless job for user?

**Comment by mexicarne** [comment]
Ok, it looks like gimp_update168.gmic is created automatically on first GMIC plugin run. So these files not need to be installed manually.

**Comment by dtschump** [comment]
The `gimp_update168.gmic` is indeed downloaded automatically by the plug-in at startup, so you don't have to install it manually (except if you have a zealous firewall, that happens on Windows).
The `cli_update168.gmic` file is the update file for the CLI interface `gmic`. It is not downloaded automatically, but you can get it by invoking `gmic` with the `-update` option : 

    $ gmic -update

Then, `cli_update168.gmic` should be present in your `$HOME/.config.gmic/`.

**Comment by mexicarne** [comment]
Thank you for clarifications. Sadly, while invoking `gmic` I got this:
```
[rm@smsh-zfs ~]> gmic -update
Segmentation fault (core dumped)
```
and the same without any options:
```
[rm@smsh-zfs ~]> gmic 
Segmentation fault (core dumped)
```
Would you please point me how to debug the cause?

**Comment by dtschump** [comment]
Ah, that's annoying indeed.
If that is possible, I suggest then compiling then `gmic` in "debug" mode : 

    $ cd gmic/src
    $ make debug
    $ ./gmic -update -debug

It will possibly tell what is going wrong
(should be very verbose). If you can copy/paste the terminal messages somewhere, that could be of help !

**Comment by dtschump** [comment]
As I didn't get more info on this issue, I'm closing it.
