### ISSUE TITLE
[suggestion] Implement filter box to quickly find effects by name

### ISSUE THREAD

**Issue by hamoid** [dtschump/gmic-minimal#5]
G'mic includes so many filters (456 currently) that it can be hard to remember where to find the one we are looking for. It would be great to have a filter-search box on top of the list, so one could type part of a name to show only matched filters. 

For instance, by typing "fish" I would see "Fish-eye", or by typing "upscale" I would see the 3 available upscale filters.

**Comment by dtschump** [comment]
There is already such a simple search filter, in section 'About/'. See screenshot:
http://i.imgur.com/dQc3AMl.png

**Comment by hamoid** [comment]
Nice, I didn't know about it. Thanks. I think it's a great start, but not ideal for several reasons: 
* It's hidden inside about (it never came to my mind to look there for a search function)
* You need to press update. Ideally the results would auto-update and the button could be removed
* Currently it tells you where the filter is, but it does not take you there. So you still have to search for the suggested section yourself, scan with your eyes up and down until you find it.

If I may, I suggest adding a text box above "Available Filters (456)" without any further buttons. When you type in it, the number of Available Filters (X) updates in real time to reflect the number of results. The results would not be collapsed to eliminate a few more clicks.

That way it would be just two steps: type in the filter box, click on the resulting filter and use it.

For an example of a working version, type "point" in the first text box at http://funprogramming.org/ and see how the list updates.

**Comment by dtschump** [comment]
I know that's not ideal indeed :)
Anyway, except if someone decides to implement a better alternative, we'll probably have to stick with it. Implementing a user-friendly filter search engine represents a lot of work, and I won't have the time to do this personally.

**Comment by hamoid** [comment]
I understand :) If someone wanted to give it a try, which files should be looked at? Are there build instructions already somewhere? 

Thanks for your work on G'mic :+1:

**Comment by dtschump** [comment]
All the code of the GIMP plug-in interface is contained in the single file : 

https://github.com/dtschump/gmic-minimal/blob/master/src/gmic_gimp.cpp
